CREATE TABLE clients (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    builder_id              UUID NOT NULL REFERENCES builders(id),
    first_name              VARCHAR(100) NOT NULL,
    last_name               VARCHAR(100),
    company_name            VARCHAR(200),
    occupation              VARCHAR(100),
    address1                TEXT,
    address2                TEXT,
    address3                TEXT,
    city                    VARCHAR(100),
    phone_office            VARCHAR(20),
    phone_residence         VARCHAR(20),
    mobile1                 VARCHAR(20),
    mobile2                 VARCHAR(20),
    email1                  VARCHAR(150),
    email2                  VARCHAR(150),
    pan_number              VARCHAR(20),
    aadhaar_number          VARCHAR(20),
    dob                     DATE,
    date_of_marriage        DATE,
    dnd_no_call             BOOLEAN DEFAULT FALSE,
    dnd_only_email          BOOLEAN DEFAULT FALSE,
    comm_address1           TEXT,
    comm_address2           TEXT,
    comm_address3           TEXT,
    comm_city               VARCHAR(100),
    name_plate_info         VARCHAR(300),
    particulars             TEXT,
    created_at              TIMESTAMP DEFAULT now(),
    updated_at              TIMESTAMP DEFAULT now()
);
