CREATE TABLE bookings (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    builder_id          UUID NOT NULL REFERENCES builders(id),
    booking_code        VARCHAR(30) UNIQUE NOT NULL,
    flat_id             UUID NOT NULL REFERENCES flats(id),
    client_id           UUID NOT NULL REFERENCES clients(id),
    broker_id           UUID REFERENCES brokers(id),
    executive_id        UUID REFERENCES users(id),
    file_no             VARCHAR(50),
    booking_date        DATE NOT NULL,
    consideration_amt   DECIMAL(15,2) DEFAULT 0,
    scheme              VARCHAR(100),
    parking_info        TEXT,
    reference           TEXT,
    is_bare_flat        BOOLEAN DEFAULT FALSE,
    particulars         TEXT,
    status              VARCHAR(20) DEFAULT 'ACTIVE',
    created_at          TIMESTAMP DEFAULT now(),
    updated_at          TIMESTAMP DEFAULT now()
);
